// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserServiceAPI.DAL;

namespace UserServiceAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230817115445_FirstMig")]
    partial class FirstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("UserServiceAPI.DAL.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "new test user",
                            CreateDate = new DateTime(2023, 8, 17, 14, 54, 45, 189, DateTimeKind.Local).AddTicks(3745),
                            Email = "Test@mail.com",
                            NickName = "BurBon"
                        },
                        new
                        {
                            Id = 2,
                            Comments = "second test user",
                            CreateDate = new DateTime(2023, 8, 17, 14, 54, 45, 189, DateTimeKind.Local).AddTicks(8905),
                            Email = "Test1@mail.com",
                            NickName = "Turbo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
