// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserServiceAPI.DAL;

namespace UserServiceAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("UserServiceAPI.DAL.Entity.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "Test@mail.com",
                            Comments = "new test user",
                            CreateDate = new DateTime(2023, 8, 18, 14, 20, 12, 599, DateTimeKind.Local).AddTicks(7006),
                            NickName = "BurBon"
                        },
                        new
                        {
                            Email = "Test1@mail.com",
                            Comments = "second test user",
                            CreateDate = new DateTime(2023, 8, 18, 14, 20, 12, 600, DateTimeKind.Local).AddTicks(2234),
                            NickName = "Turbo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
